from .dashboard import dashboard
from .registration import register
from .member import members
from .earning import earnings
from .expenses import expenses
from .secretary import secretaries
from .orientation_attendance import orientation_attendance
from .branches import *
from .contact_person import *
from .batches import *
from .inventory import *